### ISSUE TITLE
Infinty cycle

### ISSUE THREAD

**Issue by M1LKYWVY** [kirmanak/SPLTest#1]
@Azavod, @kirmanak, у меня такое смутное подозрение, что
 `void foreach(struct node* root, int(*func)(int) ){
	while (root != NULL){
		root->value = func(root->value);
		foreach (root->first_child, func);
		foreach (root->second_child, func);
	}
}` 
уйдет в **_бесконечный цикл_**, так как ссылочке на parent_node не присваивается **_ничего нового_**. Она всегда будет не нулль. Если не прав - поправь.

**Comment by azavodov** [comment]
вроде не должно...
мы же повторно вызываем функцию уже для дочерних узлов,
и когда мы дойдем до листьев, они будут NULL

2018-01-23 22:07 GMT+03:00 Ruslan Filichkin <notifications@github.com>:

**Comment by M1LKYWVY** [comment]
@Azavod, Да, все верно. Если условно, то она дойдет до самого нижнего узла и дальше не пойдет, но потом она начнет возвращаться вверх по адресу возврата вплоть до первой вызванной `foo`, где
нет никаких обновлений ссылки `root,` т.е. самое первое условие `while (root != NULL)` повторится.
